from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

import yaml


ALGORITHM_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = ALGORITHM_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from elderly_monitoring.modules.mental_health.submodules.facial_affect_clue.dstm_preprocess import (  # noqa: E402
    DSTM_TEMPORAL_SCHEMA_VERSION,
    DSTMTemporalConfig,
    audit_dstm_temporal_artifacts,
    build_dstm_temporal_sequence,
    write_dstm_temporal_artifact,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build leakage-neutral thesis onset-to-apex DSTM flow artifacts."
    )
    parser.add_argument(
        "--input-manifest",
        type=Path,
        default=ALGORITHM_ROOT
        / "data/manifests/microexpression/paper_v2/flow_artifact_manifest_smic_hs_classification_combined_v2.jsonl",
    )
    parser.add_argument(
        "--sequence-manifest",
        type=Path,
        default=ALGORITHM_ROOT
        / "data/manifests/microexpression/sequence_manifest_v1.jsonl",
        help="Original frame-directory manifest used only to resolve raw frame paths.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=ALGORITHM_ROOT / "data/processed/microexpression/paper_v2/dstm_temporal_apex_v2",
    )
    parser.add_argument(
        "--output-manifest",
        type=Path,
        default=ALGORITHM_ROOT
        / "data/manifests/microexpression/paper_v2/dstm_temporal_flow_artifact_manifest_smic_hs_v2.jsonl",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=ALGORITHM_ROOT / "configs/training/microexpression_paper_v2/dstm_smic_paper_exact.yaml",
    )
    parser.add_argument("--limit", type=int)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    temporary.replace(path)


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows),
        encoding="utf-8",
    )
    temporary.replace(path)


def main() -> int:
    args = parse_args()
    raw_config = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    config = DSTMTemporalConfig(**raw_config["temporal_artifact"])
    records = load_jsonl(args.input_manifest)
    source_records = load_jsonl(args.sequence_manifest)
    source_by_id = {str(record["sample_id"]): record for record in source_records}
    if len(source_by_id) != len(source_records):
        raise RuntimeError("The sequence manifest contains duplicate sample ids")
    merged_records: list[dict[str, Any]] = []
    for record in records:
        if record.get("sample_role") != "classification":
            continue
        source = source_by_id.get(str(record["sample_id"]))
        if source is None:
            raise RuntimeError(f"No raw frame mapping for {record['sample_id']}")
        merged = dict(source)
        merged.update(record)
        for field in ("frame_dir", "sequence_id", "source_dataset", "subject_id", "label", "label_name"):
            if field not in source:
                raise RuntimeError(f"Raw frame mapping for {record['sample_id']} lacks {field}")
            merged[field] = source[field]
        merged_records.append(merged)
    records = merged_records
    if args.limit is not None:
        records = records[: args.limit]
    if not records:
        raise RuntimeError("No classification records are available")

    output_records: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []
    for index, record in enumerate(records, start=1):
        relative = Path(str(record["source_dataset"])) / str(record["subject_id"])
        output_path = args.output_root / relative / f"{record['sample_id']}.npz"
        try:
            if output_path.exists() and not args.overwrite:
                with output_path.open("rb"):
                    pass
                # Existing artifacts are loaded through the source record contract
                # only when they were generated by this task; a stale file is not
                # silently accepted.
                raise FileExistsError(
                    f"{output_path} exists; pass --overwrite to regenerate it"
                )
            sequence, metadata = build_dstm_temporal_sequence(record, config=config)
            output_records.append(write_dstm_temporal_artifact(sequence, metadata, output_path))
            print(f"[{index}/{len(records)}] {record['sample_id']} T={sequence.shape[0]}")
        except Exception as error:  # noqa: BLE001
            failures.append(
                {
                    "sample_id": str(record.get("sample_id")),
                    "error": repr(error),
                }
            )
            print(f"[{index}/{len(records)}] FAILED {record.get('sample_id')}: {error}")

    audit = audit_dstm_temporal_artifacts(output_records)
    audit["source_manifest"] = args.input_manifest.resolve().as_posix()
    audit["source_manifest_sha256"] = __import__("hashlib").sha256(
        args.input_manifest.read_bytes()
    ).hexdigest()
    audit["config"] = config.as_dict()
    audit["config_sha256"] = config.fingerprint()
    audit["failures"] = failures
    audit["status"] = "pass" if not failures and audit["status"] == "pass" else "failed"

    write_jsonl(args.output_manifest, output_records)
    audit_path = args.output_manifest.with_name(
        "dstm_temporal_flow_artifact_audit_smic_hs_v2.json"
    )
    write_json(audit_path, audit)
    summary = {
        "schema_version": DSTM_TEMPORAL_SCHEMA_VERSION,
        "task_id": "MODEL-ME-006",
        "status": audit["status"],
        "sample_count": len(output_records),
        "failure_count": len(failures),
        "manifest_path": args.output_manifest.resolve().as_posix(),
        "audit_path": audit_path.resolve().as_posix(),
        "config_sha256": config.fingerprint(),
    }
    write_json(
        args.output_manifest.with_name("dstm_temporal_flow_preprocess_summary_smic_hs_v2.json"),
        summary,
    )
    print(json.dumps({"summary": summary, "audit": audit}, ensure_ascii=False, indent=2))
    return 0 if audit["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
