"""Missing-aware mood-social fusion models."""

from .oof_table import (
    FusionOOFConfig,
    FusionOOFError,
    FusionOOFInputs,
    build_fusion_oof_table,
    load_fusion_oof_config,
    load_fusion_oof_inputs,
    train_fusion_oof_table,
)
from .masked_stacking import (
    MaskedStackingConfig,
    MaskedStackingError,
    MaskedStackingInputs,
    MaskedStackingModel,
    build_fusion_features,
    confidence_from_coefficients,
    effective_evidence,
    evidence_combination,
    load_masked_stacking_config,
    load_masked_stacking_inputs,
    masked_stacking_sample_weights,
    train_masked_stacking,
)
from .optimization import (
    CALIBRATION_METHODS,
    V2_VARIANTS,
    FusionOptimizationError,
    OptimizationConfig,
    load_optimization_config,
    load_optimization_inputs,
    optimize_fusion,
)
from .deployment_optimization import (
    CANDIDATE_IDS,
    DeploymentOptimizationConfig,
    DeploymentOptimizationError,
    DeploymentSafeFusionModel,
    load_deployment_optimization_config,
    load_deployment_optimization_inputs,
    optimize_deployment_fusion,
)

__all__ = [
    "FusionOOFConfig",
    "FusionOOFError",
    "FusionOOFInputs",
    "build_fusion_oof_table",
    "load_fusion_oof_config",
    "load_fusion_oof_inputs",
    "train_fusion_oof_table",
    "MaskedStackingConfig",
    "MaskedStackingError",
    "MaskedStackingInputs",
    "MaskedStackingModel",
    "build_fusion_features",
    "confidence_from_coefficients",
    "effective_evidence",
    "evidence_combination",
    "load_masked_stacking_config",
    "load_masked_stacking_inputs",
    "masked_stacking_sample_weights",
    "train_masked_stacking",
    "CALIBRATION_METHODS",
    "V2_VARIANTS",
    "FusionOptimizationError",
    "OptimizationConfig",
    "load_optimization_config",
    "load_optimization_inputs",
    "optimize_fusion",
    "CANDIDATE_IDS",
    "DeploymentOptimizationConfig",
    "DeploymentOptimizationError",
    "DeploymentSafeFusionModel",
    "load_deployment_optimization_config",
    "load_deployment_optimization_inputs",
    "optimize_deployment_fusion",
]
